name: Sync Lecture Notes

on:
  schedule:
    - cron: '34 12 * * 2'  # 每周二12：34运行一次（错峰）
  push:
    branches:
      - main  # 当 main 分支有 push 时运行

jobs:
  sync-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Lecture Site repository
        uses: actions/checkout@v2

      - name: Checkout Lecture Notes repository
        uses: actions/checkout@v2
        with:
          repository: StephenQSstarThomas/Lecture-Notes
          path: Lecture-Notes

      - name: Sync Markdown Files
        run: |
          mkdir -p docs/Notes
          mkdir -p docs/about
          rsync -av --include='*/' --include='*.md' --exclude='README.md' --exclude='*' Lecture-Notes/ docs/Notes/
          cp Lecture-Notes/README.md docs/about/index.mdx

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs/Notes docs/about
          git diff --quiet && git diff --staged --quiet || git commit -m "Sync Lecture Notes"
          git push